export const SET_INSPECTOR = 'SET_INSPECTOR';
export const UPDATE_CANVAS = 'UPDATE_CANVAS';
export const UPDATE_RECT_SIZE = 'UPDATE_RECT_SIZE';
export const UPDATE_TB_SIZE = 'UPDATE_TB_SIZE';
export const UPDATE_BC_SIZE = 'UPDATE_BC_SIZE';
export const UPDATE_RECT_POSITION = 'UPDATE_RECT_POSITION';
export const UPDATE_TB_POSITION = 'UPDATE_TB_POSITION';
export const UPDATE_BC_POSITION = 'UPDATE_BC_POSITION';
export const UPDATE_RECT = 'UPDATE_RECT';
export const UPDATE_TB = 'UPDATE_TB';
export const UPDATE_BC = 'UPDATE_BC';
export const ADD_RECTANGLE = 'ADD_RECTANGLE';
export const ADD_BARCODE = 'ADD_BARCODE';
export const ADD_TEXTBOX = 'ADD_TEXTBOX';
export const SET_VIEW_LABEL = 'SET_VIEW_LABEL';
export const DELETE_RECTANGLE = 'DELETE_RECTANGLE';
export const DELETE_TEXTBOX = 'DELETE_TEXTBOX';
export const DELETE_BARCODE = 'DELETE_BARCODE';

export default {
  SET_INSPECTOR,
  UPDATE_CANVAS,
  UPDATE_RECT_SIZE,
  UPDATE_TB_SIZE,
  UPDATE_BC_SIZE,
  UPDATE_RECT_POSITION,
  UPDATE_TB_POSITION,
  UPDATE_BC_POSITION,
  ADD_RECTANGLE,
  ADD_BARCODE,
  ADD_TEXTBOX,
  UPDATE_RECT,
  UPDATE_TB,
  UPDATE_BC,
  SET_VIEW_LABEL,
  DELETE_RECTANGLE,
  DELETE_TEXTBOX,
  DELETE_BARCODE
};
