export const GET_DATABASE_REQUEST = 'GET_DATABASE_REQUEST';
export const GET_DATABASE_FAILURE = 'GET_DATABASE_FAILURE';
export const GET_DATABASE_SUCCESS = 'GET_DATABASE_SUCCESS';

export default {
  GET_DATABASE_REQUEST,
  GET_DATABASE_FAILURE,
  GET_DATABASE_SUCCESS
};
