export const GET_LABEL_REQUEST = 'GET_LABEL_REQUEST';
export const GET_LABEL_FAILURE = 'GET_LABEL_FAILURE';
export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const POST_LABEL_REQUEST = 'POST_LABEL_REQUEST';
export const POST_LABEL_SUCCESS = 'POST_LABEL_SUCCESS';
export const POST_LABEL_FAILURE = 'POST_LABEL_FAILURE';
export const DELETE_LABEL_REQUEST = 'DELETE_LABEL_REQUEST';
export const DELETE_LABEL_SUCCESS = 'DELETE_LABEL_SUCCESS';
export const DELETE_LABEL_FAILURE = 'DELETE_LABEL_FAILURE';
export const GET_PDF_REQUEST = 'GET_PDF_REQUEST';
export const GET_PDF_SUCCESS = 'GET_PDF_SUCESS';
export const GET_PDF_FAILURE = 'GET_PDF_FAILURE';

export default {
  GET_LABEL_REQUEST,
  GET_LABEL_FAILURE,
  GET_LABEL_SUCCESS,
  POST_LABEL_REQUEST,
  POST_LABEL_SUCCESS,
  POST_LABEL_FAILURE,
  DELETE_LABEL_REQUEST,
  DELETE_LABEL_SUCCESS,
  DELETE_LABEL_FAILURE,
  GET_PDF_REQUEST,
  GET_PDF_SUCCESS,
  GET_PDF_FAILURE
};
