export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const SET_INSPECTOR = 'SET_INSPECTOR';
export const UPDATE_OBJECT = 'UPDATE_OBJECT';
export const UPDATE_SIZE = 'UPDATE_SIZE';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const ADD_OBJECT = 'ADD_OBJECT';

export default {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  GET_PRODUCTS_REQUEST,
  GET_PRODUCTS_FAILURE,
  GET_PRODUCTS_SUCCESS,
  UPDATE_OBJECT,
  UPDATE_SIZE,
  UPDATE_POSITION,
  ADD_OBJECT
};
