export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const ADD_TEXT_BOX = 'ADD_TEXT_BOX';
export const ADD_RECTANGLE = 'ADD_RECTANGLE';
export const UPDATE_RECTANGLE_POSITION = 'UPDATE_RECTANGLE_POSITION';
export const UPDATE_TEXTBOX_POSITION = 'UPDATE_TEXTBOX_POSITION';
export const UPDATE_RECTANGLE_SIZE = 'UPDATE_RECTANGLE_SIZE';
export const UPDATE_TEXTBOX_SIZE = 'UPDATE_TEXTBOX_SIZE';
export const SET_INSPECTOR = 'SET_INSPECTOR';
export const UPDATE_RECTANGLE = 'UPDATE_RECTANGLE';
export const UPDATE_TEXTBOX = 'UPDATE_TEXTBOX';

export default {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  GET_PRODUCTS_REQUEST,
  GET_PRODUCTS_FAILURE,
  GET_PRODUCTS_SUCCESS,
  ADD_TEXT_BOX,
  ADD_RECTANGLE,
  UPDATE_RECTANGLE_POSITION,
  UPDATE_TEXTBOX_POSITION,
  UPDATE_RECTANGLE_SIZE,
  UPDATE_TEXTBOX_SIZE,
  UPDATE_RECTANGLE,
  UPDATE_TEXTBOX
};
