image: node:latest

stages:
  - lint
  - test

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    - eslint --init
    # Run ESLint
    - eslint src/**/*.js src/**/*.jsx

Test:
  stage: test
  script:
    - npm test