image: node:latest

stages:
  - lint
  - test

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm i eslint \
      eslint-config-airbnb
    # Run ESLint
    - eslint src/**/*.js src/**/*.jsx