# For jobs only run on master with protected runners
.only-master:
  only:
    - master
  tags:
    - protected

image: docker:19.03.1

variables:
  GITLAB_BUILD_IMAGE_LATEST: label-creator:latest

before_script:
  - npm i

stages:
  - lint
  - test
  - build

Lint:
  stage: lint
  script:
    - npm run lint

Test:
  stage: test
  script:
    - yarn test --coverage --watchAll=false

Build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build .
    - docker push $GITLAB_BUILD_IMAGE_LATEST
  extends:
    - .only-master
